allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  # Nuxt
  - '@nuxt/*'
  - '@nuxtjs/*'
  - '@nuxthub/*'
  - 'nuxt'
  - 'nuxt-*'
  - 'nuxtseo-*'
  # Cloudflare
  - '@cloudflare/*'
  - 'wrangler'
  - 'workerd'
  - 'miniflare'
